MVC/MVC/Controllers/IntroductionController/ProductIntroductionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers.IntroductionController
{
    public class ProductIntroductionController : Controller
    {

        //Sofas(current)
        //Chairs(current)
        //Tables(current)
        //Beds(current)
        //Cabinet And Dressingtable(current)
        //Accessories
        // GET: ProductIntroduction
        public ActionResult Sofas()
        {
            return View();
        }
        public ActionResult Chairs()
        {
            return View();
        }
        public ActionResult Tables()
        {
            return View();
        }
        public ActionResult Beds()
        {
            return View();
        }
        public ActionResult CabinetAndDressingtable()
        {
            return View();
        }
        public ActionResult Accessories()
        {
            return View();
        }
    }
}

MVC/MVC/Controllers/ProductListController.cs
using MVC.Models;
using MVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class ProductListController : Controller
    {
        // GET: ProductList
        public ActionResult Index()
        {

            using (mvcContext db = new mvcContext())
            {

                string sqlQuery = @"select p.ProductID ,p.ProductName,ps.Price,ps.Image,p.Quantity
                                    from Products p
                                    join  (select *
                                    from(
	                                    select ROW_NUMBER()OVER(PARTITION BY [ProductID],[Price] ORDER by [ProductID])as rown,*
	                                    FROM [ProductSpecifications])AS T1
	                                    WHERE rown = 1) ps 
                                    on ps.ProductID=p.ProductID";
                var Results = db.Database.SqlQuery<ProductListViewModels>(sqlQuery).ToList();
                return View(Results);
            }
        }
    }
}

MVC/MVC/Views/ProductIntroduction/Accessories.cshtml
@{
    ViewBag.Title = "Accessories";
}

<div class="content">
    <div class="category_image ">
        <div class="category_img w-100">
            <img src="https://res-5.cloudinary.com/dwpujv6in/image/upload/c_pad,dpr_2.0,f_auto,q_auto/v1/media/catalog/tmp/category/WebM2_CategoryLandingPages_Marquees_AccessoriesNov18.jpg"
                 alt="" class="image w-100 ">
        </div>
        <div class="category_content">
            <h4 class="text-center">New Accessories Designs</h4>
            <a href="~/ProductList/Category?type=14">
                <img src="~/Assest/img/InformationImg/Collet Rug-頁面大圖.jpg"
                     alt="Rugs" class="image w-100">
                <h6>Rugs</h6>
            </a>
            <a href="~/ProductList/Category?type=15">
                <img src="~/Assest/img/InformationImg/Duck Duck 20 Square Pillow-頁面大圖.jpg"
                     alt="Pillows And Cushionss" class="image w-100">
                <h6>Pillows And Cushionss</h6>
            </a>
            <a href="~/ProductList/Category?type=16">
                <img src="~/Assest/img/InformationImg/Last Chance Mirror-頁面大圖.jpg"
                     alt="Mirrors" class="image w-100">
                <h6>Mirrors</h6>
                <p>5 SHAPES, 3 COLORS</p>
            </a>
            <a href="~/ProductList/Category?type=17">
                <img src="~/Assest/img/InformationImg/Chaperone Wool Throw-頁面大圖.jpg"
                     alt="Bedding" class="image w-100">
                <h6>Bedding</h6>
            </a>
        </div>

    </div>
    <div class="category_menu ">
        <div class="category_menu_content">
            <div class="home_link">
                <a href="#">Home</a>
                <span>| Modern Accessories</span>
            </div>
            <h1>Accessories</h1>
            <ul>
                <li>
                    @Html.ActionLink("Rugs", "Category", "ProductList", new { type = 14 }, new { sortOrder = ViewBag.ResetParm })
                </li>
                <li>
                    @Html.ActionLink("Pillows And Cushionss", "Category", "ProductList", new { type = 15 }, new { sortOrder = ViewBag.ResetParm })
                </li>
                <li>
                    @Html.ActionLink("Mirrors", "Category", "ProductList", new { type = 16 }, new { sortOrder = ViewBag.ResetParm })
                </li>
                <li>
                    @Html.ActionLink("Bedding", "Category", "ProductList", new { type = 17 }, new { sortOrder = ViewBag.ResetParm })
                </li>
            </ul>
        </div>
    </div>
</div>
@section topCSS{
    <link href="~/Assest/css/Introduction.css" rel="stylesheet" />
    @*<link href="~/Content/Chart.css" rel="stylesheet" />*@
    <style>
        li a {
            color: black;
            text-decoration: none;
        }

            li a:hover {
                color: black;
                text-decoration: none;
            }
    </style>
}

MVC/MVC/Views/ProductIntroduction/Beds.cshtml
@{
    ViewBag.Title = "Beds";
}

<div class="content">
    <div class="category_image ">
        <div class="category_img w-100">
            <img src="~/Assest/img/InformationImg/Lovely Linen Throw-頁面大圖.jpg"
                 alt="" class="image w-100 ">
        </div>
        <div class="category_content">
            <h4 class="text-center">Beds Designs</h4>
            <a href="~/ProductList/Category?type=10">
                <img src="~/Assest/img/InformationImg/Hunker King Bed-頁面大圖.jpg"
                     alt="Bedroom-Beds" class="image w-100">
                <h6>Bedroom-Beds</h6>
            </a>
            <a href="~/ProductList/Category?type=11">
                <img src="~/Assest/img/InformationImg/Me Time Twin Bed-頁面大圖.jpg"
                     alt="Kids-Beds" class="image w-100">
                <h6>Kids-Beds</h6>
            </a>
        </div>

    </div>
    <div class="category_menu ">
        <div class="category_menu_content">
            <div class="home_link">
                <a href="#">Home</a>
                <span>| Modern Office Furniture</span>
            </div>
            <h1>Beds</h1>
            <ul>
                <li>
                    @Html.ActionLink("Bedroom-Beds", "Category", "ProductList", new { type = 10 }, new { sortOrder = ViewBag.ResetParm })
                </li>
                <li>
                    @Html.ActionLink("Kids-Beds", "Category", "ProductList", new { type = 11 }, new { sortOrder = ViewBag.ResetParm })
                </li>
            </ul>
        </div>
    </div>
</div>
@section topCSS{

    <link href="~/Assest/css/Introduction.css" rel="stylesheet" />
    <style>
        li a {
            color: black;
            text-decoration: none;
        }

            li a:hover {
                color: black;
                text-decoration: none;
            }
    </style>
}

MVC/MVC/Views/ProductIntroduction/CabinetAndDressingtable.cshtml
@{
    ViewBag.Title = "CabinetAndDressingtable";
}

<div class="content">
    <div class="category_image ">
        <div class="category_img w-100">
            <img src="~/Assest/img/InformationImg/Chicago 8 Box-頁面大圖.jpg"
                 alt="" class="image w-100 ">
        </div>
        <div class="category_content">
            <h4 class="text-center">Cabinet And Dressingtable Designs</h4>
            <a href="~/ProductList/Category?type=12">
                <img src="~/Assest/img/InformationImg/Lap 2 Door  Credenza-頁面大圖.jpg"
                     alt="Dressers" class="image w-100">
                <h6>Dressers</h6>
            </a>
            <a href="~/ProductList/Category?type=13">
                <img src="~/Assest/img/InformationImg/Browser Low Bookcase-頁面大圖.jpg"
                     alt="Bookcases" class="image w-100">
                <h6>Bookcases</h6>
            </a>
        </div>

    </div>
    <div class="category_menu ">
        <div class="category_menu_content">
            <div class="home_link">
                <a href="#">Home</a>
                <span>| Modern Office Furniture</span>
            </div>
            <h1>Cabinet And Dressingtable</h1>
            <ul>
                <li>
                    @Html.ActionLink("Dressers", "Category", "ProductList", new { type = 12 }, new { sortOrder = ViewBag.ResetParm })
                </li>
                <li>
                    @Html.ActionLink("Bookcases", "Category", "ProductList", new { type = 13 }, new { sortOrder = ViewBag.ResetParm })
                </li>
            </ul>
        </div>
    </div>
</div>
@section topCSS{

    <link href="~/Assest/css/Introduction.css" rel="stylesheet" />
    <style>
        li a {
            color: black;
            text-decoration: none;
        }

            li a:hover {
                color: black;
                text-decoration: none;
            }
    </style>
}

MVC/MVC/Views/ProductIntroduction/Chairs.cshtml
@{
    ViewBag.Title = "Chairs";
}

<div class="content">
    <div class="category_image ">

        <div class="category_img w-100">
            <img src="~/Assest/img/InformationImg/Deep Thoughts Leather Chaise-頁面大圖.jpg"
                 alt="" class="image w-100 ">
        </div>
        <div class="category_content">
            <h4 class="text-center">New Chairs Designs</h4>
            <a href="~/ProductList/Category?type=3">
                <img src="~/Assest/img/InformationImg/Nonesuch Swivel Leather Lounge Chair-頁面大圖.jpg"
                     alt="Lounge Chairs" class="image w-100">
                <h6>Lounge Chairs</h6>
            </a>
            <a href="~/ProductList/Category?type=4">
                <img src="~/Assest/img/InformationImg/Bumper Large Ottoman-頁面大圖.jpg"
                     alt="Ottomans And Stools" class="image w-100">
                <h6>Ottomans And Stools</h6>
            </a>
            <a href="~/ProductList/Category?type=5">
                <img src="~/Assest/img/InformationImg/Daybench-頁面大圖.jpg"
                     alt="Benches" class="image w-100">
                <h6>Benches</h6>
                <p>AVAILABLE IN KING AND QUEEN</p>
            </a>
            <a href="~/ProductList/Category?type=6">
                <img src="~/Assest/img/InformationImg/Daily Task Chair-頁面大圖.jpg"
                     alt="Kids-Chairs" class="image w-100">
                <h6>Kids-Chairs</h6>
                <p>AVAILABLE IN KING AND QUEEN</p>
            </a>
        </div>

    </div>
    <div class="category_menu ">
        <div class="category_menu_content">
            <div class="home_link">
                <a href="#">Home</a>
                <span>| Modern Bedroom Furniture</span>
            </div>
            <h1>Chairs</h1>
            <ul>
                <li>
                    @Html.ActionLink("Lounge Chairs", "Category", "ProductList", new { type = 3 }, new { sortOrder = ViewBag.ResetParm })
                </li>
                <li>
                    @Html.ActionLink("Ottomans And Stools", "Category", "ProductList", new { type = 4 }, new { sortOrder = ViewBag.ResetParm })
                </li>
                <li>
                    @Html.ActionLink("Benches", "Category", "ProductList", new { type = 5 }, new { sortOrder = ViewBag.ResetParm })
                </li>
                <li>
                    @Html.ActionLink("Kids-Chairs", "Category", "ProductList", new { type = 6 }, new { sortOrder = ViewBag.ResetParm })
                </li>
            </ul>
        </div>
    </div>
</div>

@section topCSS{

    <link href="~/Assest/css/Introduction.css" rel="stylesheet" />
    <style>
        li a {
            color: black;
            text-decoration: none;
        }

            li a:hover {
                color: black;
                text-decoration: none;
            }
    </style>
}

MVC/MVC/Views/ProductIntroduction/Sofas.cshtml
@{
    ViewBag.Title = "Sofas";
}

<div class="content">
    <div class="category_image ">
        <div class="category_img w-100">
            <img src="https://res-2.cloudinary.com/dwpujv6in/image/upload/c_pad,dpr_2.0,f_auto,q_auto/v1/media/catalog/tmp/category/WebM2_CategoryLandingPages_Marquees_Living_Nov18.jpg"
                 alt="" class="image w-100 ">
        </div>
        <div class="category_content">
            <h4 class="text-center">New Sofa Designs</h4>
            <a href="~/ProductList/Category?type=1">
                <img src="~/Assest/img/InformationImg/Bobber Floor Lamp-頁面大圖.jpg"
                     alt="Sofas And Sleeper" class="image w-100">
                <h6>Sofas And Sleeper</h6>
            </a>
            <a href="~/ProductList/Category?type=2">
                <img src="~/Assest/img/InformationImg/Bloke Armless Velvet Sofa with Chaise-頁面大圖.jpg"
                     alt="Sectional Sofas" class="image w-100">
                <h6>Sectional Sofas</h6>
                <p>NEW DESIGN</p>
            </a>
        </div>

    </div>
    <div class="category_menu ">
        <div class="category_menu_content">
            <div class="home_link">
                <a href="#">Home</a>
                <span>| Modern Living Room Furniture</span>
            </div>
            <h1>Sofas</h1>
            <ul>
                <li>
                    @Html.ActionLink("Sofas And Sleeper", "Category", "ProductList", new { type = 1 }, new { sortOrder = ViewBag.ResetParm })
                </li>
                <li>
                    @Html.ActionLink("Sectional Sofas", "Category", "ProductList", new { type = 2 }, new { sortOrder = ViewBag.ResetParm })
                </li>
            </ul>
        </div>
    </div>


</div>
@section topCSS{

    <link href="~/Assest/css/Introduction.css" rel="stylesheet" />
    <style>
        li a {
            color: black;
            text-decoration: none;
        }

            li a:hover {
                color: black;
                text-decoration: none;
            }
    </style>
}

MVC/MVC/Views/ProductIntroduction/Tables.cshtml
@{
    ViewBag.Title = "Tables";
}


<div class="content">
    <div class="category_image ">

        <div class="category_img w-100">
            <img src="https://res-3.cloudinary.com/dwpujv6in/image/upload/c_pad,dpr_2.0,f_auto,q_auto/v1/media/catalog/tmp/category/WebM2_CategoryLandingPages_Marquees_Dining_Nov18.jpg"
                 alt="" class="image w-100 ">
        </div>
        <div class="category_content">
            <h4 class="text-center">New Tables Designs</h4>
            <a href="~/ProductList/Category?type=7">
                <img src="~/Assest/img/InformationImg/Circula Large Coffee Table-頁面大圖.jpg"
                     alt="Accent And Coffee Tables" class="image w-100">
                <h6>Accent And Coffee Tables</h6>
            </a>
            <a href="~/ProductList/Category?type=8">
                <img src="~/Assest/img/InformationImg/Cant Desk-頁面大圖.jpg"
                     alt="Office-Desks And Tables" class="image w-100">
                <h6>Office-Desks And Tables</h6>
            </a>
            <a href="~/ProductList/Category?type=9">
                <img src="~/Assest/img/InformationImg/Stash Desk-kids-頁面大圖.jpg"
                     alt="Kids-Desk" class="image w-100">
                <h6>Kids-Desk</h6>
            </a>
        </div>

    </div>
    <div class="category_menu ">
        <div class="category_menu_content">
            <div class="home_link">
                <a href="#">Home</a>
                <span>| Modern Dining Room Furniture</span>
            </div>
            <h1>Tables</h1>
            <ul>
                <li>
                    @Html.ActionLink("Accent And Coffee Tables", "Category", "ProductList", new { type = 7 }, new { sortOrder = ViewBag.ResetParm })
                </li>
                <li>
                    @Html.ActionLink("Office-Desks And Tables", "Category", "ProductList", new { type = 8 }, new { sortOrder = ViewBag.ResetParm })
                </li>
                <li>
                    @Html.ActionLink("Kids-Desk", "Category", "ProductList", new { type = 9 }, new { sortOrder = ViewBag.ResetParm })
                </li>
            </ul>
        </div>
    </div>
</div>

@section topCSS{

    <link href="~/Assest/css/Introduction.css" rel="stylesheet" />
    <style>
        li a {
            color: black;
            text-decoration: none;
        }

            li a:hover {
                color: black;
                text-decoration: none;
            }
    </style>
}